=== GossJS/15092017-vasily-kowalev/part_03/part_03.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT statistics (ip | visits | ips)+>
    <!ELEMENT ip EMPTY>
    <!ATTLIST ip
        addr CDATA #REQUIRED
        frequency CDATA #REQUIRED
        title CDATA #IMPLIED
    >
    <!ELEMENT visits (computers | mobile_devices)+>
        <!ELEMENT computers (os+)>
            <!ELEMENT os (#PCDATA)>
            <!ATTLIST os name CDATA #REQUIRED>

        <!ELEMENT mobile_devices (device+)>
            <!ELEMENT device (#PCDATA)>
            <!ATTLIST device name CDATA #REQUIRED>
    <!ELEMENT ips (ip+)>
    <!ATTLIST ips title CDATA #REQUIRED>

=== GossJS/15092017-vasily-kowalev/part_03/part_03.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE statistics PUBLIC "part_03" "part_03.dtd">
<statistics>
    <ip title="Самый частый IP-адрес" addr="077.234.203.101" frequency="12"/>
    <visits>
        <computers>
            <os name="Windows">87</os>
            <os name="Linux">8</os>
            <os name="Mac OS">6</os>
        </computers>
        <mobile_devices>
            <device name="iPhone with Mac OS">5</device>
            <device name="iPad with Mac OS">1</device>
            <device name="Mobiles with Android">10</device>
        </mobile_devices>
    </visits>
    <ips title="5 наиболее встречающихся адресов в порядке убывания частоты">
        <ip addr="077.234.203.101" frequency="12"/>
        <ip addr="005.144.096.251" frequency="11"/>
        <ip addr="081.222.086.058" frequency="6"/>
        <ip addr="094.019.018.060" frequency="4"/>
        <ip addr="005.164.066.173" frequency="4"/>
    </ips>
</statistics>
